import os
from PIL import Image, ImageChops

#out = '_outliers'
out = ''
val='val'
image_files = [
        f'{val}_dtocean_plots/kde2d_dtocean{out}.png',
        f'{val}_dtland_plots/kde2d_dtland{out}.png',
        f'{val}_dbdeep_plots/kde2d_dbdeep{out}.png'
        ]
out_file = f'{val}_all_plots/kde2d_all{out}.png'

os.makedirs(f'{val}_all_plots',exist_ok=True)


def trim_white_background(img):
    """
    Finds the bounding box of non-white pixels and crops the image.
    Handles transparent backgrounds (RGBA) generated by matplotlib.
    """
    # If the image has an alpha (transparency) channel, convert it to solid white RGB
    if img.mode in ('RGBA', 'LA') or (img.mode == 'P' and 'transparency' in img.info):
        bg = Image.new('RGB', img.size, (255, 255, 255))
        bg.paste(img, (0, 0), img.convert('RGBA'))
        img_rgb = bg
    else:
        img_rgb = img.convert('RGB')

    # Create a pure white image of the same size
    white_bg = Image.new('RGB', img_rgb.size, (255, 255, 255))
    
    # Find the difference between the image and the white background
    diff = ImageChops.difference(img_rgb, white_bg)
    
    # Get the bounding box of the non-zero (non-white) regions
    bbox = diff.getbbox()
    
    if bbox:
        return img.crop(bbox) # Crop the original image using the calculated bounding box
    
    return img # Return original if completely blank

# Open all images, trim them, and check their sizes
images = []
widths = []
heights = []

for file in image_files:
    if os.path.exists(file):
        img = Image.open(file)
        
        # --- CROP THE WHITESPACE HERE ---
        img = trim_white_background(img)
        
        images.append(img)
        widths.append(img.width)
        heights.append(img.height)
    else:
        print(f"Warning: File {file} not found!")

if not images:
    print("No images found!")
    exit()

# Get the max height and total width for horizontal appending
total_height = sum(heights)
max_width = max(widths)

# You might want to increase this gap now that the borders are completely removed!
gap = 25 
total_height += gap * (len(images) - 1)

# Create a new blank white image
combined = Image.new('RGB', (max_width, total_height), (255, 255, 255))

# Paste each image side-by-side
y_offset = 0
for img in images:
    # If heights vary after cropping, you can center them vertically by doing:
    # x_offset = (max_width - img.width) // 2
    # combined.paste(img, (x_offset, y_offset))
    
    combined.paste(img, (0, y_offset))
    y_offset += img.height + gap

# Save the combined image
combined.save(out_file)
print(f"Images combined and saved as {out_file}")
